### ISSUE TITLE
step predictions and data leakage

### ISSUE THREAD

**Issue by bmreiniger** [alegonz/baikal#15]
It looks like you use the same, entire, dataset for each step.  But then the inputs to steps beyond the first layer are the "predictions" from models on their own training sets, which seems prone to data leakage and overfitting.  See e.g. mlxtend's `StackingClassifier` vs. `StackingCVClassifier`.

**Comment by alegonz** [comment]
Yes, I'm already aware of this, thank you. I am already working on updating the examples and a new API for supporting out-of-fold predictions in the first level. Please refer to the discussion on Issue #13 for more details.

**Comment by alegonz** [comment]
Stacks following the standard protocol (and not prone to data leakage) are now possible with the new API release in version 0.3.0. Please refer [here](https://baikal.readthedocs.io/en/stable/examples.html#stacked-classifiers-standard-protocol) for an example.
