### ISSUE TITLE
how to access one of the parent object

### ISSUE THREAD

**Issue by rja172** [alegonz/baikal#59]
Any suggestion on how to setup this kind of workflow
1. Fit_transform an Ordinal Encoder to transform Y 
2. Train Model (X and Transformed Y)
3. Inverse Transfrom Predicted (Transformed) Y to original Y 

Challenge: Step 3 requires access to OrdinalEncoder trained at step 1

**Comment by alegonz** [comment]
Please take a look at [the transformed target example in the documentation](https://baikal.readthedocs.io/en/stable/examples.html#transformed-target). That should be similar to the case you outlined. Feel free to reopen if that didn't help.
